### ISSUE TITLE
Logical evaluation- should be 'or' instead of 'and'?

### ISSUE THREAD

**Issue by navedrizvi** [williamfiset/data-structures#30]
https://github.com/williamfiset/data-structures/blob/c2ca86a8f881c3aab5b1a3ff81d186000ba44c83/com/williamfiset/datastructures/dynamicarray/DynamicArray.java#L52

**Comment by williamfiset** [comment]
Yup, looks like a bug to me. @navedrizvi want to give a crack at submitting a pull request to fix this?

**Comment by navedrizvi** [comment]
Yes will do. Thanks for the course though, really enjoying it!
