### ISSUE TITLE
reverse method in dynamic intArray

### ISSUE THREAD

**Issue by Pasupatirajesh** [williamfiset/data-structures#38]
The reverse method in the dynamic integer array doesn't seem to work as intended. The for loop doesn't print all elements of the array as it loops only half of the array when printing the contents.

**Comment by williamfiset** [comment]
Would you like to send a PR to fix it?

**Comment by Pasupatirajesh** [comment]
I have the method working as intended as it has originally been written. Should have waited to check before opening an issue. This can be closed.
