### ISSUE TITLE
[UnionFind] No need to update sz of the merged component?

### ISSUE THREAD

**Issue by toypiano** [williamfiset/data-structures#39]
Hi William, 

Thank you for creating such great course and it tremendously helped me to understand algorithms and data structure.
I have a question about your implementation of the UnionFind DS but it looks like the questions at the Udemy Q&A section haven't been answered for some time, so I figured I would have a better chance of reaching you here.

In the UnionFind source code, you are merging the smaller component into the bigger one and updating the sz  of the bigger component, but the sz of the smaller component is not being updated. Is it not necessary to update it to be zero since it doesn't have any element belonging to it?

```java
// Unify the components/sets containing elements 'p' and 'q'
  public void unify(int p, int q) {

    int root1 = find(p);
    int root2 = find(q);

    // These elements are already in the same group!
    if (root1 == root2) return;

    // Merge smaller component/set into the larger one.
    if (sz[root1] < sz[root2]) {
      sz[root2] += sz[root1];
      id[root1] = root2;
    } else {
      sz[root1] += sz[root2];
      id[root2] = root1;
    }

    // Since the roots found are different we know that the
    // number of components/sets has decreased by one
    numComponents--;
  }
}
```

Thank you again for the great course.
Many of us owe a great deal.

**Comment by williamfiset** [comment]
Great question, follow the thread here for an answer:

https://github.com/williamfiset/Algorithms/issues/127
