### ISSUE TITLE
Missing data structures

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/data-structures#8]
- [ ] AVL tree
- [ ] B-Tree
- [x] Binary tree
- [x] Bloom filter
- [x] D-Heap
- [x] Dynamic Array
- [ ] Fenwick Tree
  - [x] Point updates and range sum queries
  - [x] Range updates and point queries
  - [ ] Range updates and range queries
- [ ] Fibonacci heap
- [x] Graph
  - [x] Adjacency matrix
  - [x] Adjacency list
- [x] Hashtable
  - [x] Separate chaining with linked list
  - [x] Open addressing linear probing
  - [x] Open addressing quadratic probing
  - [x] Open addressing double hashing probing
- [ ] Judy array
- [ ] K-d Tree
- [ ] Link-cut tree
- [x] Linked-list
- [x] Binary heap
- [x] QuadTree (optional)
- [x] Queue
  - [x] Link list implementation
  - [x] Array implementation
- [ ] Red-Black tree
- [ ] Segment tree
  - [ ] Array based implementation with lazy propagation
  - [x] Pointer based with lazy propagation
  - [ ] With coordinate compression
- [x] Set
- [x] Skip list
- [ ] Splay Tree
- [x] Stack
  - [x] Pointer based implementation
  - [x] Array based implementation
- [ ] SuffixArray
  - [x] O(n<sup>2</sup>log(n)) implementation
  - [x] O(nlog<sup>2</sup>(n)) implementation
  - [x] O(nlog(n)) implementation
  - [ ] O(n) implementation
- [ ] Treap
- [x] Trie
- [x] Unionfind (with path compression)
- [ ] Van Emde Boas tree

**Comment by Braj65** [comment]
Hi,
I have understanding about
Fenwick Tree- Range updates and point queries
Segment tree- Array based implementation with lazy propagation
Let me know if you want me to contribute.

**Comment by williamfiset** [comment]
@Braj65 we would love your contribution! Feel free to submit a pull request with the new DS(s) you had in mind!

**Comment by williamfiset** [comment]
Closing this and adding individual issues for each DS
